name: Build MacOS

on: [push, pull_request]

jobs:
  build:
    name: Build
    runs-on: macos-latest
    strategy:
      matrix:
        toolchain:
          - nightly
        target:
          - x86_64-apple-darwin
          - aarch64-apple-darwin
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install toolchain
        uses: actions-rs/toolchain@v1
        with:
          target: ${{ matrix.target }}
          toolchain: ${{ matrix.toolchain }}
          override: true
      - name: Cargo build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --target=${{ matrix.target }}
      - name: Upload the built artifact
        uses: actions/upload-artifact@v2
        with:
          name: ddns-rs-${{ matrix.target }}
          path: target/${{ matrix.target }}/release/ddns-rs
          retention-days: 7
