name: Build Linux

on: [push, pull_request]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain:
          - nightly
        target:
          - aarch64-unknown-linux-gnu
          - i686-unknown-linux-gnu
          - x86_64-unknown-linux-gnu
          - armv7-unknown-linux-gnueabihf
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install packages
        run: |
          sudo dpkg --add-architecture arm64
          sudo dpkg --add-architecture armhf
          sudo dpkg --add-architecture i386
          sudo apt-get update
          sudo apt-get install -y -q openssl libssl-dev
          sudo apt-get clean
      - name: Install toolchain
        uses: actions-rs/toolchain@v1
        with:
          target: ${{ matrix.target }}
          toolchain: ${{ matrix.toolchain }}
          override: true
      - name: Cargo build
        uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: build
          args: --release --target=${{ matrix.target }}
      - name: Upload the built artifact
        uses: actions/upload-artifact@v2
        with:
          name: ddns-rs-${{ matrix.target }}
          path: target/${{ matrix.target }}/release/ddns-rs
          retention-days: 7
